input {
  tcp {
    port  => 5044
    codec => json_lines
  }
}

filter {
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "${LOGSTASH_ES_USER:}"
    password => "${LOGSTASH_ES_PASSWORD:}"
    index => "junes-logs-%{+YYYY.MM.dd}"
  }
}
